### ISSUE TITLE
Geburstagskind rolle bei birthday? :thinking:

### ISSUE THREAD

**Issue by CYix1** [timschumi/TUMbot#65]
Wie wäre es mit einer custom rolle, die jeder kriegt sobald man Geburstag hat?
(und natürlich auch wieder entfernen nach 0 Uhr) 
P.S:
Geburstagspinguin natürlich

**Comment by timschumi** [comment]
Closed in c24ab7f5cb9dec73ace59c91444e936c087b979c.
