### ISSUE TITLE
Permanent Birthday Role (Bug)

### ISSUE THREAD

**Issue by talemke** [timschumi/TUMbot#74]
Changing your birthday-date on your birthday will result in the date being updated in the database, but the role will not be removed. This leads to the bot not removing the birthday-role at midnight and thus one will keep the role until the next birthday.

**Possible Solution:** Check if the user changing their birthday currently has the role, and if so, remove it.

**Comment by timschumi** [comment]
Fixed in 8b7d16818e27486ff170c77e93d8b9666265730c.
